# Generated by Django 4.0.4 on 2025-06-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_emp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.CharField(blank=True, default=10000, max_length=25, null=True),
        ),
    ]
